version: '3.7'
services:
  resium:
    build: .
    image: resium-api:latest
    ports:
      - 8000:8000
    networks:
      - resium_net
      - global_net
    volumes:
      - /home/hsowan/data/resium/download:/resium/download
      - /home/hsowan/data/resium/logs:/resium/logs
    restart: always
    container_name: resium-api
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
      - /home/hsowan/data/resium/download:/download
    networks:
      - resium_net
#    ports:
#      - 6666:4444
    restart: always
    user: root
    container_name: resium-selenium

networks:
  resium_net:
  global_net:
    external: true