version: '3.7'
services:
  csdnbot:
    build: .
    image: csdnbot
    ports:
      - 8055:80
    networks:
      - mysql_net
    volumes:
      - /srv/csdnbot/download:/csdnbot/download
    command: ['nginx', '-g', 'daemon off;']
    container_name: csdnbot
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
      - /srv/csdnbot/download:/download
    networks:
      - mysql_net
    ports:
      - 6666:4444
    restart: always
    user: root
    container_name: csdnbot-selenium

networks:
  mysql_net:
    external: true