# Generated by Django 3.0.2 on 2020-01-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=6, unique=True)),
                ('invited_code', models.CharField(max_length=6)),
                ('active', models.BooleanField(db_column='is_active', default=False)),
                ('code', models.CharField(max_length=6)),
                ('valid_count', models.IntegerField(default=0)),
                ('used_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=50)),
                ('out_trade_no', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.FloatField()),
                ('paid_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('resource_url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'db_table': 'download_record',
            },
        ),
    ]
