# Generated by Django 3.0.2 on 2020-02-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_amount', models.FloatField()),
                ('purchase_count', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('expire_time', models.DateTimeField()),
                ('code', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='Csdnbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'csdnbot',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.CharField(default=None, max_length=200, null=True, verbose_name='资源地址')),
                ('title', models.CharField(max_length=100, verbose_name='资源标题')),
                ('filename', models.CharField(max_length=100, verbose_name='资源文件名')),
                ('desc', models.TextField(default=None, null=True, verbose_name='资源描述')),
                ('size', models.IntegerField(verbose_name='资源文件大小')),
                ('category', models.CharField(max_length=100, verbose_name='资源分类')),
                ('key', models.CharField(max_length=200, verbose_name='资源存储文件')),
                ('tags', models.CharField(max_length=240, verbose_name='资源标签')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_amount', models.FloatField()),
                ('purchase_count', models.IntegerField()),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('invite_code', models.CharField(max_length=6, verbose_name='邀请码')),
                ('invited_code', models.CharField(max_length=6, verbose_name='受邀请码')),
                ('return_invitor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('valid_count', models.IntegerField(default=0, verbose_name='可用下载数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已用下载数')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject', models.CharField(max_length=50)),
                ('out_trade_no', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.FloatField()),
                ('paid_time', models.DateTimeField(null=True)),
                ('pay_url', models.TextField()),
                ('purchase_count', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('coupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resource_url', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'db_table': 'download_record',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User'),
        ),
    ]
