# Generated by Django 3.0.2 on 2020-03-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='local_path',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='资源本地保存路径'),
        ),
    ]
