# Generated by Django 3.0.2 on 2020-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_auto_20200201_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
