# Generated by Django 3.0.2 on 2020-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_resource_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_download',
            field=models.BooleanField(default=False, verbose_name='是否可以下载其他站点的资源'),
        ),
    ]
