# Generated by Django 3.0.2 on 2020-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_auto_20200107_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(null=True),
        ),
    ]
