# Generated by Django 3.0.2 on 2020-02-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_auto_20200201_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csdnbot',
        ),
    ]
