# Generated by Django 3.0.2 on 2020-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='GitHub邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
