# Generated by Django 3.0.2 on 2020-03-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_auto_20200327_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_email',
        ),
    ]
