# Generated by Django 3.0.2 on 2020-01-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_auto_20200108_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pay_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
