# Generated by Django 3.0.2 on 2020-02-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_auto_20200202_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_downloading',
            field=models.BooleanField(default=False),
        ),
    ]
