# Generated by Django 3.0.2 on 2020-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_auto_20200109_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
