# Generated by Django 3.0.2 on 2020-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_remove_user_github_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
