# Generated by Django 3.0.2 on 2020-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_user_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
