# Generated by Django 3.0.2 on 2020-01-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_order_purchase_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
