# Generated by Django 3.0.2 on 2020-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_remove_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('total_amount', models.FloatField()),
                ('purchase_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
