# Generated by Django 3.0.2 on 2020-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_auto_20200202_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.IntegerField(default=1),
        ),
    ]
