# Generated by Django 3.0.2 on 2020-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_auto_20200329_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_in_count',
            field=models.SmallIntegerField(default=0, verbose_name='签到次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_check_in_today',
            field=models.BooleanField(default=False, verbose_name='今日是否签到'),
        ),
    ]
