# Generated by Django 3.0.2 on 2020-02-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_resource_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='临时密码'),
        ),
    ]
