# Generated by Django 3.0.2 on 2020-01-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_service'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
