# Generated by Django 3.0.2 on 2020-03-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_auto_20200329_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_id',
        ),
    ]
