# Generated by Django 3.0.2 on 2020-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_user_temp_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=50, verbose_name='账号登录名')),
                ('password', models.CharField(max_length=50, verbose_name='账号密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='账号唯一昵称')),
                ('email', models.EmailField(max_length=254)),
                ('is_using', models.BooleanField(default=False, verbose_name='是否在使用中')),
                ('cookies', models.TextField()),
            ],
            options={
                'db_table': 'baidu_account',
            },
        ),
        migrations.CreateModel(
            name='CsdnAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('github_username', models.CharField(max_length=50)),
                ('github_password', models.CharField(max_length=50)),
                ('csdn_username', models.CharField(max_length=50)),
                ('csdn_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_using', models.BooleanField(default=False, verbose_name='是否在使用中')),
                ('cookies', models.TextField()),
            ],
            options={
                'db_table': 'csdn_account',
            },
        ),
    ]
