# Generated by Django 3.0.2 on 2020-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_user_wx_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
