# Generated by Django 3.0.2 on 2020-01-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_csdnbot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csdnbot',
        ),
    ]
