# Generated by Django 3.0.2 on 2020-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0012_auto_20200208_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdnaccount',
            name='csdn_phone',
        ),
        migrations.RemoveField(
            model_name='csdnaccount',
            name='csdn_username',
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='账号绑定手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name='账号唯一名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiduaccount',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='csdnaccount',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='csdnaccount',
            name='github_password',
            field=models.CharField(max_length=50, verbose_name='账号绑定的GitHub密码'),
        ),
        migrations.AlterField(
            model_name='csdnaccount',
            name='github_username',
            field=models.CharField(max_length=50, verbose_name='账号绑定的GitHub用户名'),
        ),
    ]
