# Generated by Django 3.0.2 on 2020-04-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0013_remove_user_check_in_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaobaoWenkuAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否使用该账号')),
            ],
            options={
                'db_table': 'taobao_wenku_account',
            },
        ),
    ]
