# Generated by Django 3.0.2 on 2020-02-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0013_auto_20200208_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiduaccount',
            name='is_using',
        ),
        migrations.RemoveField(
            model_name='csdnaccount',
            name='is_using',
        ),
    ]
