# Generated by Django 3.0.2 on 2020-01-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0013_csdnbot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='csdnbot',
            table='csdnbot',
        ),
    ]
