# Generated by Django 3.0.2 on 2020-04-09 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0014_taobaowenkuaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='zhiwang_type',
        ),
    ]
