# Generated by Django 3.0.2 on 2020-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0015_remove_resource_zhiwang_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QiantuAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cookies', models.TextField(default=None, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='账号拥有者的联系邮箱')),
                ('used_count', models.IntegerField(default=0, verbose_name='使用下载数')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否使用该账号')),
            ],
            options={
                'db_table': 'qiantu_account',
            },
        ),
        migrations.AlterField(
            model_name='doceraccount',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='是否使用该账号'),
        ),
    ]
