# Generated by Django 3.0.2 on 2020-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0015_downloadrecord_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiduaccount',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
