# Generated by Django 3.0.2 on 2020-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0015_resource_resourcetag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='resource',
            name='size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
