# Generated by Django 3.0.2 on 2020-02-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0016_auto_20200208_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否使用该账号'),
        ),
        migrations.AlterField(
            model_name='baiduaccount',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='使用下载数'),
        ),
        migrations.AlterField(
            model_name='csdnaccount',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='使用下载数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='temp_password',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='修改密码时保存的临时密码'),
        ),
    ]
