# Generated by Django 3.0.2 on 2020-01-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0016_auto_20200114_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='resource_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='resource',
            name='csdn_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
