# Generated by Django 3.0.2 on 2020-04-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0016_auto_20200416_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiduaccount',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='是否使用该账号'),
        ),
        migrations.AlterField(
            model_name='csdnaccount',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='是否使用该账号'),
        ),
    ]
