# Generated by Django 3.0.2 on 2020-04-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0017_auto_20200416_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=None, max_length=100, verbose_name='用户的唯一标识'),
            preserve_default=False,
        ),
    ]
