# Generated by Django 3.0.2 on 2020-01-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0017_auto_20200114_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrecord',
            name='resource_id',
        ),
    ]
