# Generated by Django 3.0.2 on 2020-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0018_remove_downloadrecord_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='csdn_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
