# Generated by Django 3.0.2 on 2020-02-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0018_baiduaccount_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrecord',
            name='account',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='使用的会员账号'),
        ),
    ]
