# Generated by Django 3.0.2 on 2020-04-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0018_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwzRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.CharField(max_length=240)),
                ('point', models.SmallIntegerField(default=0, verbose_name='消耗的积分')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
