# Generated by Django 3.0.2 on 2020-02-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0019_auto_20200212_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User'),
        ),
    ]
