# Generated by Django 3.0.2 on 2020-04-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0019_dwzrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwzrecord',
            name='generated_url',
            field=models.CharField(default=None, max_length=240, verbose_name='生成的网址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dwzrecord',
            name='url',
            field=models.CharField(max_length=240, verbose_name='原网址'),
        ),
    ]
