# Generated by Django 3.0.2 on 2020-02-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0020_resource_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invited_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='return_invitor',
        ),
    ]
