# Generated by Django 3.0.2 on 2020-04-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0020_auto_20200416_1535'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dwzrecord',
            table='dwz_record',
        ),
    ]
