# Generated by Django 3.0.2 on 2020-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0021_auto_20200416_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_device',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='temp_password',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default=None, max_length=240, verbose_name='头像地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='qq_openid',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='QQ唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
