# Generated by Django 3.0.2 on 2020-01-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0021_remove_downloadrecord_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
