# Generated by Django 3.0.2 on 2020-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0022_auto_20200215_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_audited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='资源分类'),
        ),
    ]
