# Generated by Django 3.0.2 on 2020-01-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0022_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='key',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='desc',
            field=models.TextField(),
        ),
    ]
