# Generated by Django 3.0.2 on 2020-01-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0023_auto_20200115_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
