# Generated by Django 3.0.2 on 2020-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0023_auto_20200215_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_md5',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
