# Generated by Django 3.0.2 on 2020-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0024_resource_file_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_md5',
            field=models.CharField(max_length=100),
        ),
    ]
