# Generated by Django 3.0.2 on 2020-04-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0024_auto_20200416_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=None, max_length=200, verbose_name='用来验证用户可靠性，新账号和旧账号替换'),
            preserve_default=False,
        ),
    ]
