# Generated by Django 3.0.2 on 2020-01-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0024_downloadrecord_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csdnbot',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='csdnbot',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(max_length=100, verbose_name='资源分类'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='csdn_url',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='CSDN资源地址'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='desc',
            field=models.TextField(verbose_name='资源描述'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='资源文件名'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='key',
            field=models.CharField(max_length=200, verbose_name='资源存储文件'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.IntegerField(verbose_name='资源文件大小'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=100, verbose_name='资源标题'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='service',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=6, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_code',
            field=models.CharField(max_length=6, verbose_name='受邀请码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='已用下载数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='valid_count',
            field=models.IntegerField(default=0, verbose_name='可用下载数'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_amount', models.FloatField()),
                ('purchase_count', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField()),
                ('comment', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
