# Generated by Django 3.0.2 on 2020-04-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0025_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gitee_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
