# Generated by Django 3.0.2 on 2020-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0025_auto_20200119_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(default=None, max_length=240, verbose_name='资源标签'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResourceTag',
        ),
    ]
