# Generated by Django 3.0.2 on 2020-02-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0025_auto_20200215_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='resource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='downloader.Resource'),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='resource_url',
            field=models.CharField(max_length=200, null=True, verbose_name='资源地址'),
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=240)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
