# Generated by Django 3.0.2 on 2020-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0026_auto_20200123_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='return_invitor',
            field=models.BooleanField(default=False),
        ),
    ]
