# Generated by Django 3.0.2 on 2020-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0026_auto_20200215_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecomment',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='parent',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterModelTable(
            name='resourcecomment',
            table='resource_comment',
        ),
    ]
