# Generated by Django 3.0.2 on 2020-04-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0027_remove_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=None, max_length=200, null=True, unique=True, verbose_name='用来验证用户可靠性，新账号和旧账号替换'),
        ),
    ]
