# Generated by Django 3.0.2 on 2020-01-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0027_user_return_invitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='expiration',
            new_name='expire_time',
        ),
    ]
