# Generated by Django 3.0.2 on 2020-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0027_auto_20200215_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_audited',
            field=models.SmallIntegerField(default=1),
        ),
    ]
