# Generated by Django 3.0.2 on 2020-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0028_auto_20200126_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='1c96203a3f9a11eaae33a0999b0715d5', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupon',
        ),
    ]
