# Generated by Django 3.0.2 on 2020-02-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0028_auto_20200215_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceComment',
        ),
    ]
