# Generated by Django 3.0.2 on 2020-04-18 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0028_user_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point', models.SmallIntegerField(verbose_name='签到获得的积分')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
