# Generated by Django 3.0.2 on 2020-02-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0029_delete_resourcecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_audited',
            field=models.SmallIntegerField(default=1, verbose_name='是否通过审核'),
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=240)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'db_table': 'resource_comment',
            },
        ),
    ]
