# Generated by Django 3.0.2 on 2020-04-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0029_checkinrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dwzrecord',
            name='point',
        ),
    ]
