# Generated by Django 3.0.2 on 2020-02-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0030_auto_20200216_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=100, verbose_name='昵称'),
        ),
    ]
