# Generated by Django 3.0.2 on 2020-04-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0030_remove_dwzrecord_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='baidu_user_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gitee_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
