# Generated by Django 3.0.2 on 2020-01-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0031_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.Coupon'),
        ),
    ]
