# Generated by Django 3.0.2 on 2020-04-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0031_auto_20200418_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='baidu_user_id',
            new_name='baidu_openid',
        ),
    ]
