# Generated by Django 3.0.2 on 2020-02-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0032_auto_20200217_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='has_done',
            field=models.BooleanField(default=True),
        ),
    ]
