# Generated by Django 3.0.2 on 2020-01-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0032_auto_20200126_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='账户余额'),
        ),
    ]
