# Generated by Django 3.0.2 on 2020-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0032_auto_20200418_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='baidu_openid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
