# Generated by Django 3.0.2 on 2020-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0033_auto_20200418_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dingtalk_openid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
