# Generated by Django 3.0.2 on 2020-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0033_downloadrecord_has_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrecord',
            name='has_done',
            field=models.BooleanField(default=True, verbose_name='是否下载成功'),
        ),
    ]
