# Generated by Django 3.0.2 on 2020-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0033_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='csdn_url',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_from',
            field=models.CharField(default=None, max_length=30, verbose_name='资源来源'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='资源地址'),
        ),
    ]
