# Generated by Django 3.0.2 on 2020-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0034_user_dingtalk_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coding_user_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
