# Generated by Django 3.0.2 on 2020-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0034_auto_20200217_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('link', models.CharField(max_length=240, verbose_name='推广链接')),
                ('image', models.CharField(max_length=240, verbose_name='推广图片')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
