# Generated by Django 3.0.2 on 2020-01-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0034_auto_20200130_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
