# Generated by Django 3.0.2 on 2020-01-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0035_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='has_uploaded',
            field=models.BooleanField(default=True),
        ),
    ]
