# Generated by Django 3.0.2 on 2020-02-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0035_advert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advert',
            table='advert',
        ),
    ]
