# Generated by Django 3.0.2 on 2020-01-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0036_resource_has_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='desc',
            field=models.TextField(default=None, null=True, verbose_name='资源描述'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='has_uploaded',
            field=models.BooleanField(default=True, verbose_name='是否上传至OSS'),
        ),
    ]
