# Generated by Django 3.0.2 on 2020-02-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0037_advert_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrecord',
            name='has_done',
        ),
    ]
