# Generated by Django 3.0.2 on 2020-04-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0037_auto_20200419_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocConvertRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('download_url', models.CharField(default=None, max_length=240, null=True, verbose_name='转换成功后的下载链接')),
                ('point', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User')),
            ],
            options={
                'db_table': 'doc_convert_record',
            },
        ),
        migrations.DeleteModel(
            name='ConvertRecord',
        ),
    ]
