# Generated by Django 3.0.2 on 2020-01-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0038_remove_resource_resource_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='has_uploaded',
        ),
    ]
