# Generated by Django 3.0.2 on 2020-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0038_remove_downloadrecord_has_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_device',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='登录设备'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_ip',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='登录IP'),
        ),
    ]
