# Generated by Django 3.0.2 on 2020-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0038_auto_20200419_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='osc_user_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
