# Generated by Django 3.0.2 on 2020-04-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0039_user_osc_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='osc_user_id',
        ),
    ]
