# Generated by Django 3.0.2 on 2020-02-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0040_auto_20200225_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='登录时间'),
        ),
    ]
