# Generated by Django 3.0.2 on 2020-02-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0041_user_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrecord',
            name='resource_url',
        ),
        migrations.RemoveField(
            model_name='downloadrecord',
            name='title',
        ),
    ]
