# Generated by Django 3.0.2 on 2020-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0041_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cid', models.CharField(max_length=100, verbose_name='二维码唯一标志')),
                ('has_scanned', models.BooleanField(default=False, verbose_name='判断是否使用小程序扫码')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='mp_openid',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='小程序用户唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='微信公众号用户唯一标识'),
        ),
    ]
