# Generated by Django 3.0.2 on 2020-04-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0042_auto_20200430_2014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qrcode',
            table='qr_code',
        ),
    ]
