# Generated by Django 3.0.2 on 2020-02-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0043_auto_20200226_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sid', models.CharField(max_length=50, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('class', models.CharField(max_length=50, verbose_name='班级')),
                ('grade', models.IntegerField(verbose_name='年级')),
                ('school', models.CharField(max_length=50, verbose_name='学校')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
