# Generated by Django 3.0.2 on 2020-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0043_auto_20200430_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='cid',
            field=models.CharField(max_length=100, unique=True, verbose_name='二维码唯一标志'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户的唯一标识'),
        ),
    ]
