# Generated by Django 3.0.2 on 2020-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0044_auto_20200430_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mp_session_key',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='会话密钥'),
        ),
    ]
