# Generated by Django 3.0.2 on 2020-02-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0045_auto_20200229_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default=None, max_length=100, verbose_name='学院'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default=None, max_length=50, verbose_name='专业'),
            preserve_default=False,
        ),
    ]
