# Generated by Django 3.0.2 on 2020-05-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0045_user_mp_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mp_session_key',
        ),
    ]
