# Generated by Django 3.0.2 on 2020-02-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0046_auto_20200229_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=50, unique=True, verbose_name='学号'),
        ),
    ]
