# Generated by Django 3.0.2 on 2020-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0046_remove_user_mp_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='token',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='扫码登录时保存的token'),
        ),
    ]
