# Generated by Django 3.0.2 on 2020-02-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0047_auto_20200229_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
