# Generated by Django 3.0.2 on 2020-05-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0047_qrcode_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='token',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='uid',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='扫码登录时保存的uid'),
        ),
    ]
