# Generated by Django 3.0.2 on 2020-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0048_auto_20200502_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='uid',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='扫码登录时保存的uid'),
        ),
    ]
