# Generated by Django 3.0.2 on 2020-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0049_auto_20200502_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='code_type',
            field=models.CharField(default=None, max_length=20, verbose_name='二维码类型，bing或者login'),
            preserve_default=False,
        ),
    ]
