# Generated by Django 3.0.2 on 2020-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0050_auto_20200302_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='purchase_count',
        ),
        migrations.AddField(
            model_name='coupon',
            name='point',
            field=models.IntegerField(default=0, verbose_name='下载积分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
        migrations.AddField(
            model_name='order',
            name='point',
            field=models.IntegerField(default=0, verbose_name='下载积分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='point',
            field=models.IntegerField(default=0, verbose_name='下载积分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, verbose_name='下载积分'),
        ),
        migrations.AddField(
            model_name='user',
            name='used_point',
            field=models.IntegerField(default=0, verbose_name='已积分使用'),
        ),
    ]
