# Generated by Django 3.0.2 on 2020-03-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0051_auto_20200304_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='purchase_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='used_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='valid_count',
        ),
    ]
