# Generated by Django 3.0.2 on 2020-05-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0051_freedownloadcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeDownloadCode',
        ),
    ]
