# Generated by Django 3.0.2 on 2020-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0052_auto_20200304_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='used_today',
            field=models.IntegerField(default=0, verbose_name='今日下载'),
        ),
        migrations.AlterField(
            model_name='user',
            name='used_point',
            field=models.IntegerField(default=0, verbose_name='已使用积分'),
        ),
    ]
