# Generated by Django 3.0.2 on 2020-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0052_delete_freedownloadcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='H5登录密码'),
        ),
    ]
