# Generated by Django 3.0.2 on 2020-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0053_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='sms_code',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='短信验证码'),
        ),
    ]
