# Generated by Django 3.0.2 on 2020-05-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0054_csdnaccount_sms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='driver_cookies',
            field=models.TextField(default=None, null=True, verbose_name='给driver使用的cookies'),
        ),
    ]
