# Generated by Django 3.0.2 on 2020-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0054_remove_csdnaccount_used_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiduaccount',
            name='share_doc_count',
            field=models.IntegerField(default=0, verbose_name='共享文档使用数'),
        ),
        migrations.AddField(
            model_name='baiduaccount',
            name='special_doc_count',
            field=models.IntegerField(default=0, verbose_name='VIP专享文档使用数'),
        ),
        migrations.AddField(
            model_name='baiduaccount',
            name='vip_free_count',
            field=models.IntegerField(default=0, verbose_name='VIP免费文档使用数'),
        ),
        migrations.AddField(
            model_name='resource',
            name='wenku_type',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='百度文库文档类型'),
        ),
    ]
