# Generated by Django 3.0.2 on 2020-05-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0055_csdnaccount_driver_cookies'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='is_upload_account',
            field=models.BooleanField(default=False, verbose_name='上传账号'),
        ),
    ]
