# Generated by Django 3.0.2 on 2020-03-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0055_auto_20200308_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_md5',
            field=models.CharField(max_length=100, verbose_name='文件的md5值'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
