# Generated by Django 3.0.2 on 2020-03-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0056_auto_20200308_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiduaccount',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='baiduaccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='baiduaccount',
            name='used_count',
        ),
        migrations.RemoveField(
            model_name='baiduaccount',
            name='username',
        ),
    ]
