# Generated by Django 3.0.2 on 2020-03-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0057_auto_20200308_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='zhiwang_type',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='知网文献类型(caj/pdf)'),
        ),
    ]
