# Generated by Django 3.0.2 on 2020-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0057_auto_20200511_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_unionid',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='微信开放平台唯一标识'),
        ),
    ]
