# Generated by Django 3.0.2 on 2020-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0058_user_wx_unionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_url',
            field=models.TextField(default=None, null=True, verbose_name='支付地址，小程序微信支付时不存在'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
