# Generated by Django 3.0.2 on 2020-03-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0059_auto_20200315_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='today_download_count',
            field=models.IntegerField(default=0, verbose_name='今日已下载数'),
        ),
    ]
