# Generated by Django 3.0.2 on 2020-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0059_auto_20200515_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PudnAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=254, verbose_name='登录邮箱')),
                ('password', models.EmailField(max_length=254, verbose_name='登录密码')),
                ('buy_time', models.DateTimeField(verbose_name='账号购买时间')),
                ('cookies', models.TextField(default=None, null=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否使用该账号')),
            ],
            options={
                'db_table': 'pudn_account',
            },
        ),
    ]
