# Generated by Django 3.0.2 on 2020-03-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0060_csdnaccount_today_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='used_point',
            field=models.IntegerField(default=0, verbose_name='下载使用的积分'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
