# Generated by Django 3.0.2 on 2020-05-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0060_pudnaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pudnaccount',
            name='cookies',
        ),
    ]
