# Generated by Django 3.0.2 on 2020-05-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0061_remove_pudnaccount_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wx_unionid',
        ),
    ]
