# Generated by Django 3.0.2 on 2020-06-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0062_remove_user_wx_unionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdnaccount',
            name='driver_cookies',
        ),
        migrations.RemoveField(
            model_name='csdnaccount',
            name='is_upload_account',
        ),
        migrations.RemoveField(
            model_name='csdnaccount',
            name='sms_code',
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=240)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
