# Generated by Django 3.0.2 on 2020-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0062_auto_20200320_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='zhiwang_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='zhiwang_has_caj',
            field=models.BooleanField(default=False, verbose_name='知网文献是否支持下载CAJ'),
        ),
        migrations.AddField(
            model_name='resource',
            name='zhiwang_has_pdf',
            field=models.BooleanField(default=False, verbose_name='知网文献是否支持下载PDF'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='key',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='资源存储文件'),
        ),
    ]
