# Generated by Django 3.0.2 on 2020-03-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0063_auto_20200320_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='zhiwang_has_caj',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='zhiwang_has_pdf',
        ),
        migrations.AddField(
            model_name='resource',
            name='zhiwang_type',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='知网文献类型(caj/pdf)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='download_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.IntegerField(verbose_name='资源文件大小'),
        ),
    ]
