# Generated by Django 3.0.2 on 2020-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0063_auto_20200612_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pattern',
            field=models.BooleanField(default=False, verbose_name='合作伙伴'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='管理员账号'),
        ),
    ]
