# Generated by Django 3.0.2 on 2020-03-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0064_auto_20200320_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.CharField(default=None, max_length=200, null=True, verbose_name='文章链接')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('author', models.CharField(max_length=100, verbose_name='文章作者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_md5',
            field=models.CharField(max_length=100, verbose_name='文件的md5值'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User'),
        ),
    ]
