# Generated by Django 3.0.2 on 2020-03-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0065_auto_20200320_0705'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
