# Generated by Django 3.0.2 on 2020-03-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0066_auto_20200320_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(default=None, max_length=200, null=True, unique=True, verbose_name='文章链接'),
        ),
    ]
