# Generated by Django 3.0.2 on 2020-06-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0066_auto_20200612_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='user',
            field=models.ForeignKey(default=398, on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User'),
            preserve_default=False,
        ),
    ]
