# Generated by Django 3.0.2 on 2020-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0067_auto_20200320_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default=None, max_length=240, verbose_name='文章简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP文章'),
        ),
    ]
