# Generated by Django 3.0.2 on 2020-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0067_csdnaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrecord',
            name='account',
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='csdn_id',
            field=models.IntegerField(default=None, verbose_name='CSDN ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否被禁用'),
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='valid_count',
            field=models.IntegerField(default=0, verbose_name='可用下载数'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='account_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='alipay_account',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='支付宝账号'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='支付宝账号对应的真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
