# Generated by Django 3.0.2 on 2020-06-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0068_auto_20200612_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alipay_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='can_upload',
            field=models.BooleanField(default=True, verbose_name='是否可以上传资源'),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否被用户删除'),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Resource'),
        ),
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被用户删除')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.User')),
            ],
            options={
                'db_table': 'upload_record',
            },
        ),
    ]
