# Generated by Django 3.0.2 on 2020-03-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0068_auto_20200320_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default=None, max_length=200, verbose_name='文章标签'),
            preserve_default=False,
        ),
    ]
