# Generated by Django 3.0.2 on 2020-03-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0069_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
