# Generated by Django 3.0.2 on 2020-06-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0069_auto_20200613_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrecord',
            name='account_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
