# Generated by Django 3.0.2 on 2020-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0070_auto_20200613_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdnaccount',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='csdnaccount',
            name='is_cookies_valid',
            field=models.BooleanField(default=True, verbose_name='Cookies是否有效'),
        ),
    ]
