# Generated by Django 3.0.2 on 2020-03-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0071_auto_20200320_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
