# Generated by Django 3.0.2 on 2020-06-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0071_auto_20200613_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pattern',
            field=models.BooleanField(default=False, verbose_name='合作用户'),
        ),
    ]
