# Generated by Django 3.0.2 on 2020-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0072_user_is_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='uid',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='user_id',
            field=models.IntegerField(default=None, verbose_name='扫码登录时保存的uid'),
            preserve_default=False,
        ),
    ]
