# Generated by Django 3.0.2 on 2020-03-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0073_auto_20200322_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocerPreviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.CharField(max_length=240, verbose_name='图片地址')),
                ('alt', models.CharField(max_length=200, verbose_name='图片解释')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Resource')),
            ],
            options={
                'db_table': 'docer_preview_image',
            },
        ),
    ]
