# Generated by Django 3.0.2 on 2020-06-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0074_auto_20200613_1917'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecomment',
            table='article_comment',
        ),
        migrations.DeleteModel(
            name='DwzRecord',
        ),
    ]
