# Generated by Django 3.0.2 on 2020-03-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0075_auto_20200322_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docerpreviewimage',
            old_name='alt',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='docerpreviewimage',
            old_name='url',
            new_name='image_url',
        ),
    ]
