# Generated by Django 3.0.2 on 2020-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0075_auto_20200614_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='原创'),
        ),
    ]
