# Generated by Django 3.0.2 on 2020-03-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0076_auto_20200322_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docerpreviewimage',
            old_name='image_alt',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='docerpreviewimage',
            old_name='image_url',
            new_name='url',
        ),
    ]
