# Generated by Django 3.0.2 on 2020-06-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0077_remove_pointusagerecord_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point', models.IntegerField(verbose_name='剩余积分')),
                ('used_point', models.IntegerField(default=0, verbose_name='使用积分')),
                ('add_point', models.IntegerField(default=0, verbose_name='增加积分')),
                ('comment', models.CharField(max_length=100, verbose_name='积分使用备注')),
                ('url', models.CharField(default=None, max_length=240, null=True, verbose_name='链接')),
                ('resource', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='downloader.User')),
            ],
            options={
                'db_table': 'point_record',
            },
        ),
        migrations.DeleteModel(
            name='PointUsageRecord',
        ),
    ]
