# Generated by Django 3.0.2 on 2020-03-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0077_auto_20200322_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
