# Generated by Django 3.0.2 on 2020-06-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0078_auto_20200616_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
