# Generated by Django 3.0.2 on 2020-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0081_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='性别'),
        ),
    ]
