# Generated by Django 3.0.2 on 2020-06-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0083_auto_20200617_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
