# Generated by Django 3.0.2 on 2020-06-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0084_auto_20200617_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpSwiperAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='Modal的标题')),
                ('content', models.CharField(max_length=100, verbose_name='Modal的内容')),
                ('image_url', models.CharField(max_length=200, verbose_name='swiper的图片')),
                ('clipboard_data', models.CharField(max_length=100, verbose_name='复制到剪切板的内容')),
                ('msg', models.CharField(max_length=100, verbose_name='复制成功的消息')),
            ],
            options={
                'db_table': 'mp_swiper_ad',
            },
        ),
    ]
