# Generated by Django 3.0.2 on 2020-06-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0087_auto_20200620_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mp_version', models.CharField(max_length=50, verbose_name='小程序版本')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
