# Generated by Django 3.0.2 on 2020-06-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0088_systeminfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systeminfo',
            table='system_info',
        ),
    ]
