# Generated by Django 3.0.2 on 2020-06-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0089_auto_20200620_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnaccount',
            name='unit_price',
            field=models.FloatField(default=None, null=True, verbose_name='下载单价'),
        ),
    ]
