# Generated by Django 3.0.2 on 2020-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0090_csdnaccount_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_taobao',
            field=models.BooleanField(default=False, verbose_name='是否来自淘宝'),
        ),
    ]
