# Generated by Django 3.0.2 on 2020-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0091_user_from_taobao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.TextField(default=None, null=True, verbose_name='资源标签'),
        ),
    ]
