# Generated by Django 3.0.2 on 2020-07-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0093_auto_20200701_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkcomment',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='talkcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='talkimage',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='talklike',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='talklike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
        migrations.DeleteModel(
            name='TalkComment',
        ),
        migrations.DeleteModel(
            name='TalkImage',
        ),
        migrations.DeleteModel(
            name='TalkLike',
        ),
    ]
