# Generated by Django 3.0.2 on 2020-07-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0094_auto_20200704_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MbzjAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.CharField(max_length=20, verbose_name='账号ID')),
                ('secret_key', models.CharField(max_length=100, verbose_name='用于请求接口')),
            ],
            options={
                'db_table': 'mbzj_account',
            },
        ),
    ]
