# Generated by Django 3.0.2 on 2020-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0095_mbzjaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbzjaccount',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
