# Generated by Django 3.0.2 on 2020-07-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0096_mbzjaccount_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.CharField(max_length=240, verbose_name='公告内容')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
    ]
