# Generated by Django 3.0.2 on 2020-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0097_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(verbose_name='文章简介'),
        ),
    ]
