# Generated by Django 3.0.2 on 2020-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0099_auto_20200809_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='filename',
            field=models.TextField(default=None, null=True, verbose_name='资源文件名'),
        ),
    ]
