# Generated by Django 3.2.16 on 2022-11-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0101_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.IntegerField(verbose_name='账号类型')),
                ('config', models.TextField(verbose_name='账号配置')),
                ('status', models.IntegerField(verbose_name='账号状态')),
            ],
            options={
                'db_table': 'download_account',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='gitee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qq_openid',
        ),
    ]
