# Generated by Django 3.2.16 on 2022-11-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0102_auto_20221105_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrecord',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_docer_vip_doc',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='local_path',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='wenku_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='from_taobao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_check_in_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pattern',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='登录密码'),
        ),
    ]
